---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create VPC and Subnet
      ec2_vpc:
        state: present
        region: us-east-1
        cidr_block: 20.0.0.0/16
        subnets:
          - cidr: 20.0.0.0/16
            resource_tags: {"Name":"Test Subnet"}
        route_tables:
          - subnets:
            - 20.0.0.0/16
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        wait: yes
        internet_gateway: yes
        resource_tags:
          Name: "Test VPC"
      register: vpc

    - name: get igw
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc_id }}"
        region: us-east-1
        state: present
      register: igw

    - name: Tagging the new internet gateway created
      ec2_tag:
        resource: "{{ igw.gateway_id }}"
        state: present
        region: us-east-1
        tags:
          Name: test-gateway

    - name: Create a group for our ec2 instances
      ec2_group:
        name: ansible_ssh_open
        description: an example EC2 group
        vpc_id: "{{ vpc.vpc_id }}"
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
        key_name: ansible_key
        group: ansible_ssh_open 
        instance_type: t2.micro
        image: "ami-0b33d91d"
        region: us-east-1
        vpc_subnet_id: "{{ vpc.subnets[0].id }}"
        assign_public_ip: true
        exact_count: 3
        count_tag: "ansible_instances"
        instance_tags:
          ansible_instances: "True"
          instance_number: "ec2 aws instance"
        wait: true
