---
- hosts: all
  remote_user: ec2-user
  tasks:
  - name: ping the server
    ping:
  - name: print the datetime
    command: "date"

- hosts: webserver
  become: true
  tasks:
  - name: install httpd
    yum: name=httpd
  - name: ensure httpd service is running
    service: name=httpd state=started
